#!/bin/sh -e
#
# 2020,2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of the skonfig set __nsd.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#

CONF_BASE_DIR=/etc/nsd
NSD_CONF_DIR="${CONF_BASE_DIR}/nsd.conf.d"

pattern_name=${__object_id:?}

read -r state_should <"${__object:?}/parameter/state"

# Generate slug to be used in file names
file_name_slug=$(printf '%s' "${pattern_name%.}" | tr -c 'A-Za-z0-9-.' '_')

test -n "${file_name_slug}" || {
	printf 'Slug generation failed for: %s\n' "${pattern_name}" >&2
	test -n "${pattern_name}" || printf 'Make sure the pattern\047s name is non-empty.\n' >&2
	exit 1
}

__directory "${CONF_BASE_DIR}" --state pre-exists
export require=__directory"${CONF_BASE_DIR}"

__directory "${NSD_CONF_DIR}" --state present \
	--owner 0 --group 0 --mode 0755
export require=__directory"${NSD_CONF_DIR}"

config_file="${NSD_CONF_DIR}/${file_name_slug}.pattern.conf"

if test "${state_should}" != absent
then
	printf 'pattern:\n'
	# TODO: Escape quotes??
	printf '\tname: "%s"\n' "${pattern_name}"

	# boolean options
	if test -f "${__object:?}/parameter/disallow-axfr-fallback"
	then
		printf '\tallow-axfr-fallback: no\n'
	fi
	if test -f "${__object:?}/parameter/multi-master-check"
	then
		printf '\tmulti-master-check: yes\n'
	fi

	# singleton options
	for _opt in notify-retry zonefile zonestats
	do
		# Checks
		case ${_opt}
		in
			(notify-retry)
				test -f "${__object:?}/parameter/notify" \
					 || echo 'notify-retry should be accompanied by notify.' >&2
				;;
		esac

		# Output option
		if test -s "${__object:?}/parameter/${_opt}"
		then
			printf '\t%s: %s\n' \
				"${_opt}" "$(head -n 1 "${__object:?}/parameter/${_opt}")"
		fi
	done

	# other options
	for _opt in \
		allow-notify notify outgoing-interface provide-xfr request-xfr
	do
		# Output options
		if test -s "${__object:?}/parameter/${_opt}"
		then
			sed -e "s/^/	${_opt}: /" "${__object:?}/parameter/${_opt}"
		fi
	done

	# Append --extra-options verbatim
	if test -s "${__object:?}/parameter/extra-option"
	then
		sed -e 's/^/	/' "${__object:?}/parameter/extra-option"
	fi
fi \
| __file "${config_file}" \
	  --state "${state_should}" \
	  --owner 0 --group nsd --mode 0644 \
	  --source - \
	  --onchange "nsd-checkconf ${CONF_BASE_DIR}/nsd.conf && nsd-control repattern"
# FIXME: the config file should only be updated if checkconf succeeds
