#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera@ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


CONF_BASE_DIR='/etc/nsd'
NSD_GROUP='nsd'

os=$(cat "${__global:?}/explorer/os")
state_should=$(cat "${__object:?}/parameter/state")

case $os
in
	(debian|devuan)
		package_name=nsd
		;;
	(*)
		printf "Your operating system (%s) is currently not supported by this type (%s)\n" "$os" "${__type##*/}" >&2
		printf "Please contribute an implementation for it if you can.\n" >&2
		exit 1
		;;
esac

export CDIST_ORDER_DEPENDENCY=true
__package "${package_name}" --state "${state_should}"
__start_on_boot nsd
unset CDIST_ORDER_DEPENDENCY

require=__package/"${package_name}" \
__directory "${CONF_BASE_DIR}" --state pre-exists

require=__directory/"${CONF_BASE_DIR}" \
__directory "${CONF_BASE_DIR}/nsd.conf.d" --state present \
	--owner 0 --group 0 --mode 0755
