#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of the skonfig set __nsd.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer retrieves the zonestatus.

zone_name=${__object_id:?}

nsd-control status >/dev/null 2>&1 || {
	echo 'error: nsd-control is not functional!' >&2
	exit 1
}


# NOTE: Process the zonestatus in two steps, because nsd-control prints error
#       messages on stdout.
zonestatus=$(nsd-control zonestatus "${zone_name}") || exit 0

echo "${zonestatus}" | sed -e 's/^[[:blank:]]*//' -e 's/:[[:blank:]]*/: /'
