#!/bin/sh -e
#
# 2020,2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of the skonfig set __nsd.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#

read -r state_should <"${__object:?}/parameter/state"

. "${__type:?}/files/common.sh"


__package nsd \
	--name "${package_name}" \
	--state "${state_should}"

case ${state_should}
in
	(present)
		require=__package/nsd \
		__start_on_boot nsd

		require=__package/nsd \
		__directory "${CONF_BASE_DIR:?}" \
			--state pre-exists

		require="__directory${CONF_BASE_DIR:?}" \
		__directory "${CONF_BASE_DIR:?}/nsd.conf.d" \
			--owner 0 --group 0 --mode 0755
		;;
	(absent)
		;;
esac
