#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of the skonfig set __nsd.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer retrieves the currently set options from nsd.conf

# Ignore if nsd-checkconf is missing (package might not be installed, yet)
command -v nsd-checkconf >/dev/null 2>&1 || exit 0

nsd-checkconf -v /etc/nsd/nsd.conf \
| awk '
  /^#/ { next }
  /^[a-z-]+:/ { match($0, /^[a-z-]+/); SECTION = substr($0, RSTART, RLENGTH) }
  /^\t+[^#]/ { sub(/[ \t]*/, ""); printf "%s:%s\n", SECTION, $0 }'
