#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera@ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

breify() {
	# Convert arguments to a BRE-compatible form, i.e. escape special characters
	echo "$*" | sed -e 's/[].^$*\[]/\\&/g'
}

CONF_BASE_DIR=/etc/nsd
NSD_CONF_DIR="${CONF_BASE_DIR}/nsd.conf.d"
NSD_KEY_DIR="${CONF_BASE_DIR}/nsd.key.d"


# NOTE: Due to the broken dependency-resolver in cdist, we need to reconfig nsd
#       here in gencode-remote and cannot use e.g. __check_messages.
if grep -q "^__file/$(breify "${NSD_CONF_DIR}"):" "${__messages_in:?}" \
|| grep -q "^__file/$(breify "${NSD_KEY_DIR}"):" "${__messages_in:?}"
then
	echo "nsd-checkconf '${CONF_BASE_DIR}/nsd.conf' && nsd-control reconfig || exit 1"
fi
